services:
  frontend2:
    image: 192.168.228.132:15000/sh-frontend:0.0.1
    networks:
      - sh-infra
    ports:
      - "9999:80"
    deploy:
      mode: replicated
      replicas: 1

networks:
  sh-infra:
    external: true
